<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class posts extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('posts')->insert([
            ['po_id' => 1, 'po_type' => 1, 'po_topic' => 1, 'po_title' => 'Laravel - Những điều cần nhớ', 'po_summary' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex debitis cum nulla aliquam mollitia veritatis', 'po_content' => '<p>Thực hiện Kế hoạch gi&aacute;m s&aacute;t nguồn lợi thủy sản v&agrave; ương, thả c&aacute; giống bản địa, x&acirc;y dựng mẫu ti&ecirc;u bản thủy sản năm 2015. S&aacute;ng ng&agrave;y 01/7/2015, Vườn quốc gia Tr&agrave;m Chim phối hợp với trạm thủy sản huyện Tam N&ocirc;ng tiến h&agrave;nh thả một số lo&agrave;i thủy sản ( c&aacute; tr&ecirc; v&agrave;ng, c&aacute; th&aacute;c l&aacute;c c&ograve;m ) tại ph&acirc;n khu A2 Vườn quốc gia Tr&agrave;m Chim nhằm bổ sung th&ecirc;m số lượng thủy sản b&ecirc;n trong Vườn.</p>

<p>Tại thời điểm thả c&aacute; theo đ&aacute;nh gi&aacute; của trạm thủy sản huyện Tam N&ocirc;ng m&ocirc;i trường nước tại khu A2 rất th&iacute;ch hợp để thả 02 lo&agrave;i c&aacute; n&agrave;y. Theo kế hoạch th&igrave; đợt n&agrave;y Vườn tiến h&agrave;nh thả 5.000 con c&aacute; tr&ecirc; v&agrave;ng, 4.700 con c&aacute; th&aacute;c l&aacute;c c&ograve;m v&agrave; c&aacute;c lo&agrave;i c&aacute; c&ograve;n lại như c&aacute; h&ocirc;, c&aacute; d&agrave;y sẽ tiến h&agrave;nh thả v&agrave;o khoảng th&aacute;ng 08 năm 2015 tại khu A1 Vườn quốc gia Tr&agrave;m Chim.</p>
', 'po_author' => 1, 'po_status' => 2, 'created_at' => Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at' => Carbon::now('Asia/Ho_Chi_Minh')],
            ['po_id' => 2, 'po_type' => 1, 'po_topic' => 2, 'po_title' => 'Làm thể nào để tìm được Spark joy', 'po_summary' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex debitis cum nulla aliquam mollitia veritatis', 'po_content' => '<p>Thực hiện Kế hoạch gi&aacute;m s&aacute;t nguồn lợi thủy sản v&agrave; ương, thả c&aacute; giống bản địa, x&acirc;y dựng mẫu ti&ecirc;u bản thủy sản năm 2015. S&aacute;ng ng&agrave;y 01/7/2015, Vườn quốc gia Tr&agrave;m Chim phối hợp với trạm thủy sản huyện Tam N&ocirc;ng tiến h&agrave;nh thả một số lo&agrave;i thủy sản ( c&aacute; tr&ecirc; v&agrave;ng, c&aacute; th&aacute;c l&aacute;c c&ograve;m ) tại ph&acirc;n khu A2 Vườn quốc gia Tr&agrave;m Chim nhằm bổ sung th&ecirc;m số lượng thủy sản b&ecirc;n trong Vườn.</p>

<p>Tại thời điểm thả c&aacute; theo đ&aacute;nh gi&aacute; của trạm thủy sản huyện Tam N&ocirc;ng m&ocirc;i trường nước tại khu A2 rất th&iacute;ch hợp để thả 02 lo&agrave;i c&aacute; n&agrave;y. Theo kế hoạch th&igrave; đợt n&agrave;y Vườn tiến h&agrave;nh thả 5.000 con c&aacute; tr&ecirc; v&agrave;ng, 4.700 con c&aacute; th&aacute;c l&aacute;c c&ograve;m v&agrave; c&aacute;c lo&agrave;i c&aacute; c&ograve;n lại như c&aacute; h&ocirc;, c&aacute; d&agrave;y sẽ tiến h&agrave;nh thả v&agrave;o khoảng th&aacute;ng 08 năm 2015 tại khu A1 Vườn quốc gia Tr&agrave;m Chim.</p>
', 'po_author' => 1, 'po_status' => 2, 'created_at' => Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at' => Carbon::now('Asia/Ho_Chi_Minh')],
            ['po_id' => 3, 'po_type' => 1, 'po_topic' => 1, 'po_title' => 'PHP - Ez language', 'po_summary' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex debitis cum nulla aliquam mollitia veritatis', 'po_content' => '<p>Thực hiện Kế hoạch gi&aacute;m s&aacute;t nguồn lợi thủy sản v&agrave; ương, thả c&aacute; giống bản địa, x&acirc;y dựng mẫu ti&ecirc;u bản thủy sản năm 2015. S&aacute;ng ng&agrave;y 01/7/2015, Vườn quốc gia Tr&agrave;m Chim phối hợp với trạm thủy sản huyện Tam N&ocirc;ng tiến h&agrave;nh thả một số lo&agrave;i thủy sản ( c&aacute; tr&ecirc; v&agrave;ng, c&aacute; th&aacute;c l&aacute;c c&ograve;m ) tại ph&acirc;n khu A2 Vườn quốc gia Tr&agrave;m Chim nhằm bổ sung th&ecirc;m số lượng thủy sản b&ecirc;n trong Vườn.</p>

<p>Tại thời điểm thả c&aacute; theo đ&aacute;nh gi&aacute; của trạm thủy sản huyện Tam N&ocirc;ng m&ocirc;i trường nước tại khu A2 rất th&iacute;ch hợp để thả 02 lo&agrave;i c&aacute; n&agrave;y. Theo kế hoạch th&igrave; đợt n&agrave;y Vườn tiến h&agrave;nh thả 5.000 con c&aacute; tr&ecirc; v&agrave;ng, 4.700 con c&aacute; th&aacute;c l&aacute;c c&ograve;m v&agrave; c&aacute;c lo&agrave;i c&aacute; c&ograve;n lại như c&aacute; h&ocirc;, c&aacute; d&agrave;y sẽ tiến h&agrave;nh thả v&agrave;o khoảng th&aacute;ng 08 năm 2015 tại khu A1 Vườn quốc gia Tr&agrave;m Chim.</p>
', 'po_author' => 1, 'po_status' => 2, 'created_at' => Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at' => Carbon::now('Asia/Ho_Chi_Minh')],
            ['po_id' => 4, 'po_type' => 1, 'po_topic' => 3, 'po_title' => 'Thiên nhiên chữa lành cảm xúc tôi như thế nào?', 'po_summary' => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex debitis cum nulla aliquam mollitia veritatis', 'po_content' => '<p>Thực hiện Kế hoạch gi&aacute;m s&aacute;t nguồn lợi thủy sản v&agrave; ương, thả c&aacute; giống bản địa, x&acirc;y dựng mẫu ti&ecirc;u bản thủy sản năm 2015. S&aacute;ng ng&agrave;y 01/7/2015, Vườn quốc gia Tr&agrave;m Chim phối hợp với trạm thủy sản huyện Tam N&ocirc;ng tiến h&agrave;nh thả một số lo&agrave;i thủy sản ( c&aacute; tr&ecirc; v&agrave;ng, c&aacute; th&aacute;c l&aacute;c c&ograve;m ) tại ph&acirc;n khu A2 Vườn quốc gia Tr&agrave;m Chim nhằm bổ sung th&ecirc;m số lượng thủy sản b&ecirc;n trong Vườn.</p>

<p>Tại thời điểm thả c&aacute; theo đ&aacute;nh gi&aacute; của trạm thủy sản huyện Tam N&ocirc;ng m&ocirc;i trường nước tại khu A2 rất th&iacute;ch hợp để thả 02 lo&agrave;i c&aacute; n&agrave;y. Theo kế hoạch th&igrave; đợt n&agrave;y Vườn tiến h&agrave;nh thả 5.000 con c&aacute; tr&ecirc; v&agrave;ng, 4.700 con c&aacute; th&aacute;c l&aacute;c c&ograve;m v&agrave; c&aacute;c lo&agrave;i c&aacute; c&ograve;n lại như c&aacute; h&ocirc;, c&aacute; d&agrave;y sẽ tiến h&agrave;nh thả v&agrave;o khoảng th&aacute;ng 08 năm 2015 tại khu A1 Vườn quốc gia Tr&agrave;m Chim.</p>
', 'po_author' => 1, 'po_status' => 2, 'created_at' => Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at' => Carbon::now('Asia/Ho_Chi_Minh')],
            ['po_id' => 5, 'po_type' => 2, 'po_topic' => null, 'po_title' => '[Game] Minesweeper', 'po_summary' => null, 'po_content' => '<p>Thực hiện Kế hoạch gi&aacute;m s&aacute;t nguồn lợi thủy sản v&agrave; ương, thả c&aacute; giống bản địa, x&acirc;y dựng mẫu ti&ecirc;u bản thủy sản năm 2015. S&aacute;ng ng&agrave;y 01/7/2015, Vườn quốc gia Tr&agrave;m Chim phối hợp với trạm thủy sản huyện Tam N&ocirc;ng tiến h&agrave;nh thả một số lo&agrave;i thủy sản ( c&aacute; tr&ecirc; v&agrave;ng, c&aacute; th&aacute;c l&aacute;c c&ograve;m ) tại ph&acirc;n khu A2 Vườn quốc gia Tr&agrave;m Chim nhằm bổ sung th&ecirc;m số lượng thủy sản b&ecirc;n trong Vườn.</p>

<p>Tại thời điểm thả c&aacute; theo đ&aacute;nh gi&aacute; của trạm thủy sản huyện Tam N&ocirc;ng m&ocirc;i trường nước tại khu A2 rất th&iacute;ch hợp để thả 02 lo&agrave;i c&aacute; n&agrave;y. Theo kế hoạch th&igrave; đợt n&agrave;y Vườn tiến h&agrave;nh thả 5.000 con c&aacute; tr&ecirc; v&agrave;ng, 4.700 con c&aacute; th&aacute;c l&aacute;c c&ograve;m v&agrave; c&aacute;c lo&agrave;i c&aacute; c&ograve;n lại như c&aacute; h&ocirc;, c&aacute; d&agrave;y sẽ tiến h&agrave;nh thả v&agrave;o khoảng th&aacute;ng 08 năm 2015 tại khu A1 Vườn quốc gia Tr&agrave;m Chim.</p>
', 'po_author' => 1, 'po_status' => 2, 'created_at' => Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at' => Carbon::now('Asia/Ho_Chi_Minh')],
            ['po_id' => 6, 'po_type' => 2, 'po_topic' => null, 'po_title' => '[Windows application] Sales management system', 'po_summary' => null, 'po_content' => '<p>Thực hiện Kế hoạch gi&aacute;m s&aacute;t nguồn lợi thủy sản v&agrave; ương, thả c&aacute; giống bản địa, x&acirc;y dựng mẫu ti&ecirc;u bản thủy sản năm 2015. S&aacute;ng ng&agrave;y 01/7/2015, Vườn quốc gia Tr&agrave;m Chim phối hợp với trạm thủy sản huyện Tam N&ocirc;ng tiến h&agrave;nh thả một số lo&agrave;i thủy sản ( c&aacute; tr&ecirc; v&agrave;ng, c&aacute; th&aacute;c l&aacute;c c&ograve;m ) tại ph&acirc;n khu A2 Vườn quốc gia Tr&agrave;m Chim nhằm bổ sung th&ecirc;m số lượng thủy sản b&ecirc;n trong Vườn.</p>

<p>Tại thời điểm thả c&aacute; theo đ&aacute;nh gi&aacute; của trạm thủy sản huyện Tam N&ocirc;ng m&ocirc;i trường nước tại khu A2 rất th&iacute;ch hợp để thả 02 lo&agrave;i c&aacute; n&agrave;y. Theo kế hoạch th&igrave; đợt n&agrave;y Vườn tiến h&agrave;nh thả 5.000 con c&aacute; tr&ecirc; v&agrave;ng, 4.700 con c&aacute; th&aacute;c l&aacute;c c&ograve;m v&agrave; c&aacute;c lo&agrave;i c&aacute; c&ograve;n lại như c&aacute; h&ocirc;, c&aacute; d&agrave;y sẽ tiến h&agrave;nh thả v&agrave;o khoảng th&aacute;ng 08 năm 2015 tại khu A1 Vườn quốc gia Tr&agrave;m Chim.</p>
', 'po_author' => 1, 'po_status' => 2, 'created_at' => Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at' => Carbon::now('Asia/Ho_Chi_Minh')],
            ['po_id' => 7, 'po_type' => 2, 'po_topic' => null, 'po_title' => '[Website] Mekong wild life', 'po_summary' => null, 'po_content' => '<p>Thực hiện Kế hoạch gi&aacute;m s&aacute;t nguồn lợi thủy sản v&agrave; ương, thả c&aacute; giống bản địa, x&acirc;y dựng mẫu ti&ecirc;u bản thủy sản năm 2015. S&aacute;ng ng&agrave;y 01/7/2015, Vườn quốc gia Tr&agrave;m Chim phối hợp với trạm thủy sản huyện Tam N&ocirc;ng tiến h&agrave;nh thả một số lo&agrave;i thủy sản ( c&aacute; tr&ecirc; v&agrave;ng, c&aacute; th&aacute;c l&aacute;c c&ograve;m ) tại ph&acirc;n khu A2 Vườn quốc gia Tr&agrave;m Chim nhằm bổ sung th&ecirc;m số lượng thủy sản b&ecirc;n trong Vườn.</p>

<p>Tại thời điểm thả c&aacute; theo đ&aacute;nh gi&aacute; của trạm thủy sản huyện Tam N&ocirc;ng m&ocirc;i trường nước tại khu A2 rất th&iacute;ch hợp để thả 02 lo&agrave;i c&aacute; n&agrave;y. Theo kế hoạch th&igrave; đợt n&agrave;y Vườn tiến h&agrave;nh thả 5.000 con c&aacute; tr&ecirc; v&agrave;ng, 4.700 con c&aacute; th&aacute;c l&aacute;c c&ograve;m v&agrave; c&aacute;c lo&agrave;i c&aacute; c&ograve;n lại như c&aacute; h&ocirc;, c&aacute; d&agrave;y sẽ tiến h&agrave;nh thả v&agrave;o khoảng th&aacute;ng 08 năm 2015 tại khu A1 Vườn quốc gia Tr&agrave;m Chim.</p>
', 'po_author' => 1, 'po_status' => 2, 'created_at' => Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at' => Carbon::now('Asia/Ho_Chi_Minh')],
            ['po_id' => 8, 'po_type' => 2, 'po_topic' => null, 'po_title' => '[Website] My blog - portfolio', 'po_summary' => null, 'po_content' => '<p>Thực hiện Kế hoạch gi&aacute;m s&aacute;t nguồn lợi thủy sản v&agrave; ương, thả c&aacute; giống bản địa, x&acirc;y dựng mẫu ti&ecirc;u bản thủy sản năm 2015. S&aacute;ng ng&agrave;y 01/7/2015, Vườn quốc gia Tr&agrave;m Chim phối hợp với trạm thủy sản huyện Tam N&ocirc;ng tiến h&agrave;nh thả một số lo&agrave;i thủy sản ( c&aacute; tr&ecirc; v&agrave;ng, c&aacute; th&aacute;c l&aacute;c c&ograve;m ) tại ph&acirc;n khu A2 Vườn quốc gia Tr&agrave;m Chim nhằm bổ sung th&ecirc;m số lượng thủy sản b&ecirc;n trong Vườn.</p>

<p>Tại thời điểm thả c&aacute; theo đ&aacute;nh gi&aacute; của trạm thủy sản huyện Tam N&ocirc;ng m&ocirc;i trường nước tại khu A2 rất th&iacute;ch hợp để thả 02 lo&agrave;i c&aacute; n&agrave;y. Theo kế hoạch th&igrave; đợt n&agrave;y Vườn tiến h&agrave;nh thả 5.000 con c&aacute; tr&ecirc; v&agrave;ng, 4.700 con c&aacute; th&aacute;c l&aacute;c c&ograve;m v&agrave; c&aacute;c lo&agrave;i c&aacute; c&ograve;n lại như c&aacute; h&ocirc;, c&aacute; d&agrave;y sẽ tiến h&agrave;nh thả v&agrave;o khoảng th&aacute;ng 08 năm 2015 tại khu A1 Vườn quốc gia Tr&agrave;m Chim.</p>
', 'po_author' => 1, 'po_status' => 2, 'created_at' => Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at' => Carbon::now('Asia/Ho_Chi_Minh')],
        ]);
    }
}
